export const Catalogs = [
  {
    id: 1,
    name: 'All',
    img: require('../assets/imgs/food1.jpg'),
  },
  {
    id: 2,
    name: 'Pizza',
    img: require('../assets/imgs/food3.jpg'),
  },
  {
    id: 3,
    name: 'Burger',
    img: require('../assets/imgs/food1.jpg'),
  },
  {
    id: 4,
    name: 'Asian',
    img: require('../assets/imgs/food2.jpg'),
  },
  {
    id: 5,
    name: 'Barbicuo',
    img: require('../assets/imgs/food4.jpg'),
  },
  {
    id: 6,
    name: 'Seafood',
    img: require('../assets/imgs/food2.jpg'),
  },
  {
    id: 7,
    name: 'Chicken',
    img: require('../assets/imgs/food6.jpg'),
  },
  {
    id: 8,
    name: 'Breakfast',
    img: require('../assets/imgs/food7.jpg'),
  },
];

export const products = [
  {
    id: 1,
    catalogId: 3,
    name: 'Burger Meal1',
    img: require('../assets/imgs/food1.jpg'),
    price: 50,
    type: 'Burger',
  },
  {
    id: 2,
    catalogId: 2,
    name: 'Pizza meal1',
    img: require('../assets/imgs/food3.jpg'),
    price: 30,
    type: 'Pizza',
  },
  {
    id: 3,
    catalogId: 6,
    name: 'Shrimp',
    img: require('../assets/imgs/food2.jpg'),
    price: 10,
    type: 'Seafood',
  },
  {
    id: 4,
    catalogId: 6,
    name: 'Fish',
    img: require('../assets/imgs/food4.jpg'),
    price: 10,
    type: 'Seafood',
  },
  {
    id: 5,
    catalogId: 7,
    name: 'Chicken1',
    img: require('../assets/imgs/food5.jpg'),
    price: 10,
    type: 'Chicken',
  },
  {
    id: 6,
    catalogId: 7,
    name: 'Chicken2',
    img: require('../assets/imgs/food6.jpg'),
    price: 10,
    type: 'Chicken',
  },
  {
    id: 7,
    catalogId: 8,
    name: 'Breakfast meal1',
    img: require('../assets/imgs/food7.jpg'),
    price: 10,
    type: 'Breakfast',
  },
  {
    id: 8,
    catalogId: 8,
    name: 'Breakfast meal1',
    img: require('../assets/imgs/food8.jpg'),
    price: 10,
    type: 'Breakfast',
  },
  {
    id: 9,
    catalogId: 8,
    name: 'Breakfast meal1',
    img: require('../assets/imgs/food8.jpg'),
    price: 10,
    type: 'Breakfast',
  },
  {
    id: 10,
    catalogId: 8,
    name: 'Breakfast meal1',
    img: require('../assets/imgs/food8.jpg'),
    price: 10,
    type: 'Breakfast',
  },
  {
    id: 11,
    catalogId: 8,
    name: 'Breakfast meal1',
    img: require('../assets/imgs/food8.jpg'),
    price: 10,
    type: 'Breakfast',
  },
  {
    id: 12,
    catalogId: 8,
    name: 'Breakfast meal1',
    img: require('../assets/imgs/food8.jpg'),
    price: 10,
    type: 'Breakfast',
  },
  {
    id: 13,
    catalogId: 8,
    name: 'Breakfast meal1',
    img: require('../assets/imgs/food8.jpg'),
    price: 10,
    type: 'Breakfast',
  },
  {
    id: 14,
    catalogId: 8,
    name: 'Breakfast meal1',
    img: require('../assets/imgs/food8.jpg'),
    price: 10,
    type: 'Breakfast',
  },
  {
    id: 15,
    catalogId: 8,
    name: 'Breakfast meal1',
    img: require('../assets/imgs/food8.jpg'),
    price: 10,
    type: 'Breakfast',
  },
  {
    id: 16,
    catalogId: 8,
    name: 'Breakfast meal1',
    img: require('../assets/imgs/food8.jpg'),
    price: 10,
    type: 'Breakfast',
  },
  {
    id: 17,
    catalogId: 8,
    name: 'Breakfast meal1',
    img: require('../assets/imgs/food8.jpg'),
    price: 10,
    type: 'Breakfast',
  },
  {
    id: 18,
    catalogId: 8,
    name: 'Breakfast meal1',
    img: require('../assets/imgs/food8.jpg'),
    price: 10,
    type: 'Breakfast',
  },
  {
    id: 19,
    catalogId: 8,
    name: 'Breakfast meal1',
    img: require('../assets/imgs/food8.jpg'),
    price: 10,
    type: 'Breakfast',
  },
  {
    id: 20,
    catalogId: 8,
    name: 'Breakfast meal1',
    img: require('../assets/imgs/food8.jpg'),
    price: 10,
    type: 'Breakfast',
  },
  {
    id: 21,
    catalogId: 8,
    name: 'Breakfast meal1',
    img: require('../assets/imgs/food8.jpg'),
    price: 10,
    type: 'Breakfast',
  },
  {
    id: 22,
    catalogId: 8,
    name: 'meshaltet',
    img: require('../assets/imgs/105.jpg'),
    price: 15,
    type: 'Breakfast',
  },
];
